import React from 'react';

export const AllIcon = {
  bookmarkActive:require('../../assets/icon/bookmark-01.png'),
  bookmarkInactive:require('../../assets/icon/bookmark-01-01.png'),
  backActive:require('../../assets/icon/back.png'),
  backInactive:require('../../assets/icon/back-g.png'),
  creatActive:require('../../assets/icon/creat-01.png'),
  creatInactive:require('../../assets/icon/creat-gray-01.png'),
  editActive:require('../../assets/icon/edit-01.png'),
  editInactive:require('../../assets/icon/edit-01-01.png'),
  feedActive:require('../../assets/icon/feed-01.png'),
  feedInactive:require('../../assets/icon/feed g-01.png'),
  filterActive:require('../../assets/icon/filter-01.png'),
  filterInactive:require('../../assets/icon/filterg-01.png'),
  gostoreActive:require('../../assets/icon/godiner-01.png'),
  gostoreInactive:require('../../assets/icon/godiner-01-01.png'),
  homeActive:require('../../assets/icon/home-01.png'),
  homeInactive:require('../../assets/icon/homeg-01.png'),
  likeActive:require('../../assets/icon/like-01.png'),
  likeInactive:require('../../assets/icon/like-01-01.png'),
  listActive:require('../../assets/icon/list-01.png'),
  listInactive:require( '../../assets/icon/list-01-01.png'),
  listsActive: require('../../assets/icon/lists-01-01.png'),
  listsInactive: require('../../assets/icon/lists-01.png'),
  locationActive: require('../../assets/icon/location-01.png'),
  locationInactive: require('../../assets/icon/locationg-01.png'),
  mypageActive: require('../../assets/icon/mypage-01.png'),
  mypageInactive:require( '../../assets/icon/mypageg-01.png'),
  searchActive:require( '../../assets/icon/search-01.png'),
  searchInactive:require('../../assets/icon/searchg-01.png'),
  settingsActive: require('../../assets/icon/settings-01.png'),
  settingsInactive:require('../../assets/icon/settings-01-01.png'),
  storeActive: require('../../assets/icon/diner-01.png'),
  storeInactive: require('../../assets/icon/diner-01-01.png'),
}